/* Automatically generated hashes for protobuf types */
/* Generated by proto_hashgen from UNDEFINED at Mon Jan  8 16:41:29 2024. */
namespace Motorcortex
{
	public static class Hash
	{
		public static uint Get<T>()
		{
			Type typeId = typeof(T);
			if (typeId == typeof(ParameterOffset))
			{
				return 0x37d97249;
			}
			if (typeId == typeof(Error))
			{
				return 0xcb54b842;
			}
			if (typeId == typeof(ErrorList))
			{
				return 0xa63be891;
			}
			if (typeId == typeof(ParameterInfo))
			{
				return 0x52f7c2b8;
			}
			if (typeId == typeof(GroupParameterInfo))
			{
				return 0x1d5d6a0a;
			}
			if (typeId == typeof(Header))
			{
				return 0x52e24278;
			}
			if (typeId == typeof(GroupMsg))
			{
				return 0xfe8efea8;
			}
			if (typeId == typeof(StatusMsg))
			{
				return 0xb2b3b41b;
			}
			if (typeId == typeof(LoginMsg))
			{
				return 0x630d225;
			}
			if (typeId == typeof(GetSessionTokenMsg))
			{
				return 0x4ff6b6f7;
			}
			if (typeId == typeof(SessionTokenMsg))
			{
				return 0x7c3e91ab;
			}
			if (typeId == typeof(RestoreSessionMsg))
			{
				return 0x8aef888a;
			}
			if (typeId == typeof(LogoutMsg))
			{
				return 0xd796dcd5;
			}
			if (typeId == typeof(GetParameterTreeMsg))
			{
				return 0x61d73753;
			}
			if (typeId == typeof(ParameterTreeMsg))
			{
				return 0xd31979bf;
			}
			if (typeId == typeof(GetParameterTreeHashMsg))
			{
				return 0x1711b24;
			}
			if (typeId == typeof(ParameterTreeHashMsg))
			{
				return 0xc8cef26b;
			}
			if (typeId == typeof(CreateGroupMsg))
			{
				return 0x9eab1b83;
			}
			if (typeId == typeof(GroupStatusMsg))
			{
				return 0x67aafaff;
			}
			if (typeId == typeof(RemoveGroupMsg))
			{
				return 0x7614c1ac;
			}
			if (typeId == typeof(GetParameterMsg))
			{
				return 0x985f2c2f;
			}
			if (typeId == typeof(ParameterMsg))
			{
				return 0x5815f142;
			}
			if (typeId == typeof(GetParameterListMsg))
			{
				return 0x520608a5;
			}
			if (typeId == typeof(ParameterListMsg))
			{
				return 0xadd954d9;
			}
			if (typeId == typeof(SetParameterMsg))
			{
				return 0xa78d07b6;
			}
			if (typeId == typeof(SetParameterListMsg))
			{
				return 0xe1bd5231;
			}
			if (typeId == typeof(OverwriteParameterMsg))
			{
				return 0x98505467;
			}
			if (typeId == typeof(ReleaseParameterMsg))
			{
				return 0xbb43acc2;
			}
			if (typeId == typeof(SaveMsg))
			{
				return 0xc965b56a;
			}
			if (typeId == typeof(LoadMsg))
			{
				return 0xf173d6cc;
			}
			if (typeId == typeof(ConsoleCmdMsg))
			{
				return 0x4efc6762;
			}
			if (typeId == typeof(ConsoleCmdListMsg))
			{
				return 0x96e4c2b0;
			}
			if (typeId == typeof(Unit))
			{
				return 0x1f444f39;
			}
			if (typeId == typeof(UserGroup))
			{
				return 0x651cf623;
			}
			if (typeId == typeof(Permission))
			{
				return 0xbfdf653b;
			}
			if (typeId == typeof(DataType))
			{
				return 0x62923b3a;
			}
			if (typeId == typeof(ParameterType))
			{
				return 0x2927648b;
			}
			if (typeId == typeof(StatusCode))
			{
				return 0xd785e9fa;
			}
			if (typeId == typeof(ErrorLevel))
			{
				return 0x14838051;
			}
			if (typeId == typeof(OffsetType))
			{
				return 0x74cbd84c;
			}
			if (typeId == typeof(ParameterFlag))
			{
				return 0xbcb0202c;
			}
			return 0;
		}

		public static int GetHashSize()
		{
			return 4;
		}
	}
} //namespace Motorcortex
